const double birdStartX = 100;
const double birdStartY = 100;
const double birdWidth = 60;
const double birdHeight = 40;
const double birdJumpStrength = -400;
const double gameGravity = 1200;
const double groundHeight = 200;
const double groundScrollingSpeed = 100;
const double gamePipeGap = 200;
const double gamePipeWidth = 60;
const double gameMinPipeHeight = 30;
const double gamePipeInterval = 3; // 3 seconds per pipe
